# Project information
site_name: Elemental - Immutable Linux for Rancher
site_url: https://rancher.github.io/elemental

# Repository
repo_name: rancher/elemental
repo_url: https://github.com/rancher/elemental
edit_uri: https://github.com/rancher/elemental/edit/main/docs/

theme:
  name: material
  #logo: 'assets/logo_horizontal_white.png'
  #favicon: 'assets/favicon.ico'
  palette:
    - scheme: default
      toggle:
        icon: material/eye-outline
        name: Dark Mode
    - scheme: slate
      primary: grey
      toggle:
        icon: material/eye
        name: Light Mode
  icon:
    repo: fontawesome/brands/github
  features:
    - toc.integrate

# Customization
extra:
  homepage: https://rancher.github.io/elemental
  elemental:
    slack:
      name: \#elemental
      url: https://rancher-users.slack.com/channels/elemental
    toolkit:
      name: Elemental Toolkit
      url: https://rancher.github.io/elemental-toolkit
    operator:
      name: Elemental Operator
      url: https://github.com/rancher/elemental-operator
    register:
      name: Elemental Register client
    cli:
      name: Elemental CLI
      url: https://github.com/rancher/elemental-cli/blob/main/docs/elemental.md
    iso:
      name: Elemental ISO
  ranchersystemagent:
    name: Rancher System Agent
    url: https://github.com/rancher/system-agent


#google_analytics:
plugins:
  - search
  - markdownextradata: {}

markdown_extensions:
- codehilite
- admonition
- pymdownx.details
- pymdownx.tabbed:
    alternate_style: true
- admonition
- pymdownx.snippets
- pymdownx.inlinehilite
- pymdownx.superfences
- tables
- toc:
    permalink: true

nav:
  - Overview: index.md
  - Quickstart: quickstart.md
  - Architecture: architecture.md
  - Install/Upgrade:
    - installation.md
    - upgrade.md
    - customizing.md
    - elemental-plans.md
  - Reference:
    - cloud-config-reference.md
    - machineregistration-reference.md
    - machineinventoryselectortemplate-reference.md
    - cluster-reference.md
    - elementaloperatorchart-reference.md
    - kubernetesversions.md
    - smbios.md
  - Backup:
    - backup.md
