# Project information
site_name: Elemental - Immutable Linux for Rancher
site_url: https://rancher.github.io/elemental

# Repository
repo_name: rancher/elemental
repo_url: https://github.com/rancher/elemental
edit_uri: https://github.com/rancher/elemental/edit/master/docs/

theme:
  name: material
  #logo: 'assets/logo_horizontal_white.png'
  #favicon: 'assets/favicon.ico'
  palette:
    - scheme: default
      toggle:
        icon: material/eye-outline
        name: Dark Mode
    - scheme: slate
      primary: grey
      toggle:
        icon: material/eye
        name: Light Mode
  icon:
    repo: fontawesome/brands/github
  features:
    - toc.integrate

# Customization
extra:
  homepage: https://rancher.github.io/elemental

#google_analytics:
plugins:
  - search
  - markdownextradata: {}

markdown_extensions:
- codehilite
- admonition
- pymdownx.tabbed:
    alternate_style: true
- admonition
- pymdownx.snippets
- pymdownx.inlinehilite
- pymdownx.superfences
- toc:
    permalink: true

nav:
  - Quickstart: quickstart.md
  - Overview:
    - architecture.md
    - clusters.md
  - Install/Upgrade:
    - installation.md
    - upgrade.md
    - customizing.md
    - dashboard.md
    - mcm.md
  - Reference:
    - configuration.md
    - versions.md
