name: Test build iso from simple script - PR edition

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TAG: ${{ github.SHA }}
    steps:
      - name: Install Docker
        uses: docker-practice/actions-setup-docker@v1
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y mkisofs
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build iso from script
        run: |
          # Just a simple run to test the build script, no need to upload the generated iso!
          echo "TEST" > config.yaml
          chmod +x .github/elemental-iso-build
          .github/elemental-iso-build config.yaml
      - name: Check config was inserted
        run: |
          ISO=$(find . -name "elemental-*.iso" -print)
          # Extract config and check against our config
          isoinfo -x /livecd-cloud-config.yaml -R -i $ISO > livecd-cloud-config.yaml
          # This checks that the files are the same content
          cmp config.yaml livecd-cloud-config.yaml
      - name: Basic sanity checks for ISO
        run: |
          ISO=$(find . -name "elemental-*.iso" -print)
          # Check it has eltorito
          isoinfo -d -i $ISO|grep -q Eltorito
          # check bootable flag
          isoinfo -d -i $ISO|grep -q bootable        
