name: Elemental End-To-End tests with Rancher Manager

on:
  workflow_run:
    workflows:
      - build-ci
    branches:
      - master
    types:
      - completed
  workflow_dispatch:

jobs:
  e2e-tests:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: kvm-host
    container:
      image: opensuse/leap:latest
      env:
        CLUSTER_NAME: cluster-k3s
        CLUSTER_NS: fleet-default
        INSTALL_K3S_VERSION: v1.23.9+k3s1
        INSTALL_K3S_SKIP_ENABLE: true
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
        PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        ARCH: amd64
      options: --privileged
    steps:
      - name: Install dependencies
        run: zypper -n in -l qemu-kvm libvirt virt-install curl helm git-core tar make gcc
      - name: Be sure to remove all previous data from worker ♻
        run: rm -rf ./*
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '~1.18'
      - name: Download iPXE
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          name: ipxe-artifacts
          # Force the path, this is a security hint!
          path: ./
      - name: E2E - Clean local Helm repositorie
        run: |
          # Clean Helm repo
          HELM_REPO=$(helm repo list 2>/dev/null | awk '(NR>1) { print $1 }')
          [[ -n "${HELM_REPO}" ]] && helm repo remove ${HELM_REPO} || true
      - name: E2E - Install Rancher
        run: cd tests && make e2e-install-rancher
      - name: E2E - Bootstrap node 1 with current build
        env:
          VM_INDEX: 1
        run: cd tests && make e2e-bootstrap-node
  cleanup:
    runs-on: kvm-host
    if: always()
    needs: e2e-tests
    steps:
      - name: Release space from worker ♻
        run: sudo docker system prune -f -a --volumes
