# This workflow calls the master E2E workflow with custom variables
name: Elemental E2E tests with Rancher Manager

on:
  workflow_run:
    workflows:
      - build-ci
    branches:
      - main
    types:
      - completed

concurrency:
  group: e2e-tests-${{ github.head_ref || github.ref }}-${{ github.repository }}
  cancel-in-progress: false

jobs:
  k3s:
    uses: ./.github/workflows/master-e2e.yaml
    secrets:
      credentials: ${{ secrets.GCP_CREDENTIALS }}
    with:
      cluster_name: cluster-k3s
      k8s_version_to_provision: v1.24.4+k3s1
      runner: elemental-e2e-ci-runner-spot-x86-64-2
      start_condition: ${{ github.event.workflow_run.conclusion }}
      workflow_download: ${{ github.event.workflow_run.workflow_id }}
  rke2:
    if: always()
    needs: k3s
    uses: ./.github/workflows/master-e2e.yaml
    secrets:
      credentials: ${{ secrets.GCP_CREDENTIALS }}
    with:
      cluster_name: cluster-rke2
      k8s_version_to_provision: v1.24.4+rke2r1
      ca_type: private
      runner: elemental-e2e-ci-runner-spot-x86-64-2
      start_condition: ${{ github.event.workflow_run.conclusion }}
      workflow_download: ${{ github.event.workflow_run.workflow_id }}
