name: Bootstrap RancherOS on a VM with Rancher

on:
  push:
    branches: [ master ]
    paths-ignore:
    - 'docs/**'
    - '*docs*'
    - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.QUAY_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      DOCKER_REGISTRY: quay.io
      REPO: quay.io/costoolkit/os2-ci
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Make images (container/iso/qcow2/etc.)
        run: make ci
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            dist/artifacts/*
            !dist/artifacts/*.qcow.gz
            !dist/artifacts/*.box
          if-no-files-found: error
      - name: Release space from worker â™»
        if: always()
        run: |
          sudo rm -rf build bin dist
          docker system prune -f -a --volumes
  install-with-rancher:
    runs-on: nested-virt
    needs: build
    container:
      image: opensuse/leap:latest
      env:
        CLUSTER_NAME: cluster-k3s
        CLUSTER_NS: fleet-default
        K8S_VERSION: v1.21.9+k3s1
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
      options: --privileged
    steps:
      - name: Install dependencies
        run: zypper -n in -l qemu-kvm libvirt virt-install curl helm git-core tar make
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: artifacts
      - name: Install Rancher
        run: cd tests && make install-rancher
      - name: Configure Rancher to provision RancherOS on a test server
        run: cd tests && make configure-rancher-step-01
      - name: Install RancherOS on the test server
        run: cd tests && make install-ros-node
      - name: Configure Rancher to add the test server in a test cluster
        run: cd tests && make configure-rancher-step-02
      - name: Add the test server in the test cluster
        run: cd tests && make add-node-in-cluster
      - name: Upload logs
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: k3s.log
          path: /tmp/k3s.log
          if-no-files-found: warn
