name: Release

on:
  push:
   tags:
      - 'v*'

jobs:
  build:
    runs-on: build-host
    container:
      image: ubuntu:latest
      env:
        DOCKER_USERNAME: ${{ secrets.QUAY_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
        DOCKER_REGISTRY: quay.io
        REPO: quay.io/costoolkit/os2
        # Disable KVM for Vagrant image (can be forced during execution if needed)
        NO_KVM: 1
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y sudo make curl docker.io
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Make ISO
        run: make iso
      - name: Make images (container/qcow2/etc.)
        run: make ci
      - name: Release
        uses: rancher-sandbox/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_PATH: dist/artifacts/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHR_PARALLELISM: "1"
      - name: Release space from worker â™»
        if: always()
        run: |
          sudo rm -rf build bin dist || true
          docker system prune -f -a --volumes || true
